services:
  sqldblesemployes:
    container_name: sqldblesemployes
    image: 'mysql:latest'
    #restart: unless-stopped
    environment:
      - 'MYSQL_DATABASE=lesemployes'
      - 'MYSQL_PASSWORD=admin'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=admin'
    ports:
      - '3307:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql    
    networks:
      springboot-mysql-net:
  springboot-lesinvites-compose:
    container_name: springboot-backend-lesemployes
    restart: on-failure
    depends_on:
      sqldblesemployes:
        condition: service_started
    build:
      context: .
      #dockerfile: dockerfile
    ports:
      - 8280:8080
    environment:  
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:mysql://sqldblesemployes:3306/lesemployes
      - spring.datasource.username=admin
      - spring.datasource.password=admin 
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      #- spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    networks:
      springboot-mysql-net:
networks:
   springboot-mysql-net:
   # restart: on-failure